// Generated by CoffeeScript 1.3.3
(function() {
  var Future, Iterator, util,
    __slice = [].slice;

  Future = require('fibers/future');

  util = require('util');

  module.exports = Iterator = (function() {

    function Iterator(values, options) {
      this.values = values;
      this.options = options != null ? options : {};
    }

    Iterator.prototype.futurize = function() {
      var args, fn, future,
        _this = this;
      fn = arguments[0], args = 2 <= arguments.length ? __slice.call(arguments, 1) : [];
      future = new Future();
      Fiber(function() {
        return future["return"](fn.apply(null, args));
      }).run();
      return future;
    };

    Iterator.prototype.map = function(fn, options) {
      var f, futures, i, results, v, _i, _len, _ref;
      if (options == null) {
        options = {};
      }
      results = [];
      futures = [];
      _ref = this.values;
      for (i = _i = 0, _len = _ref.length; _i < _len; i = ++_i) {
        v = _ref[i];
        if ((options.concurrency != null) && options.concurrency <= futures.length) {
          results.push(futures.shift().wait());
        }
        futures.push(this.futurize(fn, v, i));
      }
      return new Iterator(results.concat((function() {
        var _j, _len1, _results;
        _results = [];
        for (_j = 0, _len1 = futures.length; _j < _len1; _j++) {
          f = futures[_j];
          _results.push(f.wait());
        }
        return _results;
      })()));
    };

    Iterator.prototype.quickestN = function(fn, n) {
      var f, fibers, futures, i, results, v, _fn, _i, _len, _ref;
      if (n == null) {
        n = 1;
      }
      futures = (function() {
        var _i, _results;
        _results = [];
        for (f = _i = 0; 0 <= n ? _i < n : _i > n; f = 0 <= n ? ++_i : --_i) {
          _results.push(new Future());
        }
        return _results;
      })();
      fibers = [];
      _ref = this.values;
      _fn = function(v, i) {
        var fiber;
        fiber = Fiber(function() {
          var res, _j, _len1, _results;
          res = fn(v, i);
          _results = [];
          for (_j = 0, _len1 = futures.length; _j < _len1; _j++) {
            f = futures[_j];
            if (!f.isResolved()) {
              f["return"](res);
              break;
            } else {
              _results.push(void 0);
            }
          }
          return _results;
        });
        fiber.run();
        return fibers.push(fiber);
      };
      for (i = _i = 0, _len = _ref.length; _i < _len; i = ++_i) {
        v = _ref[i];
        _fn(v, i);
      }
      results = (function() {
        var _j, _results;
        _results = [];
        for (i = _j = 0; 0 <= n ? _j < n : _j > n; i = 0 <= n ? ++_j : --_j) {
          _results.push(futures[i].wait());
        }
        return _results;
      })();
      return new Iterator(results);
    };

    Iterator.prototype.quickest = function(fn) {
      return this.quickestN(fn, 1).toA()[0];
    };

    Iterator.prototype.toA = function() {
      return this.values;
    };

    return Iterator;

  })();

}).call(this);
